= Fishing for compliments
:published_at: 2006-01-04
:hp-tags: Japan

Was ist Japan's Nationalsport Nr.1? Sumo? Baseball? Golf? Manchmal scheint mir der beliebteste "Sport" für Japans Küstenbewohner das Angeln zu sein. Für mich ist Angeln kein Sport, denn ich habe mal gelernt "Mit Essen spielt man nicht!" und der Fisch am Haken hat mit Sicherheit auch nicht viel Spass an der Sache (man könnte es auch Tierquälerei nennen). Aber an Essen denkt von den Anglern, die jedes Wochenende an den Kaimauern die vordersten Plätze belegen, sowieso niemand. Jedenfalls was den Fisch betrifft, den sie gerade aus dem Wasser gezogen haben. Wahrscheinlich ist es auch besser so für die Angler, denn gesund kann das nicht sein, was so im Hafenbecken schwimmt. Es könnte sogar sein, dass sich die Fische mit Absicht ab und zu an den Haken hängen, um mal ein paar Minuten frische Luft schnappen zu können.

Andererseits tun sie einem schon auch Leid. Nicht nur die Fische, die alle paar Wochenenden zum Wiegen und Messen und als Erfolgserlebnis aus dem Wasser gezogen werden, sondern auch die Angler, die bei Wind und Wetter auf den Fang ihres Lebens warten. Und oft auch deren Ehefrauen und Kinder, die sich nebenan die Beine in den Bauch stehen und ihre Angler mit Tee und Onigiri (Reisbällchen) versorgen.

Hat dann endlich einer angebissen, dann wird er vorsichtig aus dem Wasser gezogen, stolz den Nachbarn (und der Familie) präsentiert, und darf dann wieder zurück zu seinen Freunden. Schwein gehabt!