= Ein Unglück kommt selten allein
:published_at: 2006-01-04
:hp-tags: Japan

Jetzt haben Sie mich doch gefunden! Heute Morgen haben Sie an meiner Tür geklingelt und mich aus dem Schlaf gerissen. Zwei kleine Omas standen vor der Nachbartür, und ich hatte schon eine böse Ahnung und habe versucht die Wohnungstür wieder vorsichtig zu schließen. Aber die beiden waren natürlich Profis. Sie waren zwar langsam, hatten aber guten Ohren. So leicht entkommt man ihnen nicht.

Sie haben was von "Christlich" geredet, und da dachte ich zuerst, es geht um eine Spende. Da habe ich (wie immer, wenn Vertreter etwas von mir wollen) gesagt, dass ich kaum Japanisch verstehe ... nur Deutsch. Damit hat sich die Sache normalerweise in Sekunden erledigt. Aber nicht bei diesen Omas. Die waren gut vorbereitet und hatten nach minutenlangem Blättern in Ihrem multilingualen Informationsheft die passende deutsche Seite gefunden ... mit händisch unterstrichenen Textpassagen. Respekt!

Es genügte ein kurzer Blick und es bestätigte sich meine Befürchtung: das waren Jehovas Zeugen. Lassen die einen denn nicht einmal in Japan in Frieden? Sollen sie sich doch jemanden anderen suchen, es gibt ja Millionen Ungläubige allein in Yokohama! Wie zu Hause versuchen sie auch hier, das Opfer in ein Gespräch zu verwickeln. Ja ich weiß schon, Deutschland ist bekannt für Autos und in Japan kennen sie die auch. Aber ich habe keine Lust, mich darüber an der Wohnungstür zu unterhalten. Noch dazu mit jemand, der mich soeben geweckt hat. Wie kann man nur so höflich (japanische Höflichkeitssprache) daherreden, und trotzdem so unhöflich sein und fremde Leute aus der Wohnung klingeln. Ich habe ihnen gesagt, dass es keinen Sinn macht, aber das hilft ja nichts wie jeder weiß.

Irgendwann sind sie dann doch abgezogen. Zum Glück wohnen ja noch eine Menge andere Leute in der Nähe, und so werden sie wahrscheinllich sobald nicht wieder kommen ... hoffe ich.
