= Teleshopping für Fortgeschrittene
:published_at: 2006-01-04
:hp-tags: Japan

Ja, das ist das Fernsehprogramm, das nicht ständig durch langweilige Shows, Filme und Nachrichten unterbrochen wird. In meinem Fernseher sind gleich zwei Kanäle exklusiv dafür reserviert, und damit ich mich nicht so lange durchklicken muss, kommen sie auch auf den vorderen Plätzen. Aber jetzt mal ohne Ironie: so doof ist Teleshopping gar nicht, wenn man Japanisch lernen möchte. Ich versuche mal zu erklären weshalb:

Beim Teleshopping spricht jeweils nur einer der Moderatoren und nicht ein dutzend Studiogäste auf einmal. Dieses dauernde Ineinandergequassel und die ständigen Ohhh, Ahhh, Uhhh, Oishiiii, ... Laute und gegenseitiges Bestätigen der Gäste speziell in den japanischen Shows gehen einem ziemlich schnell auf den Wecker, und man hört gar nicht mehr hin. Wenn man jedoch beim Teleshopping mal was nicht kapiert hat oder zu spät eingeschaltet, kein Sorge, es wird alles noch dutzende Male wiederholt ... bis die Zeit abgelaufen ist, oder bis sich genug Idioten gefunden haben, das Produkt zu kaufen.

Nächster Pluspunkt für Ausländer, die ein wenig zivilisiertes Japanisch lernen möchten, ist die super super höfliche Ausdrucksweise der Verkäufer (außer es läuft gerade das schlecht synchronisierte amerikanische Diätprogramm). Dieses "Hochjapanisch" wird nur noch übertroffen von Busbegleiterinnen, und Vertretern an der Haustüre.

Und für das Spassprogramm ist dann der synchronisierte Schwabe zuständig, der Hightech made in Germany verkauft: Plastikgemüsehobel, Topflappen oder Modellautos. Da ist man wirklich stolz ein Deutscher zu sein!