= Wohn-Schlaf-Koch-Ess-Klo im 10. Stock
:published_at: 2006-09-19
:hp-tags: Yokohama

----
„Wer einmal in München eine günstige Wohnung gesucht hat, den kann nichts mehr erschrecken.“
----

Diese Aussage trifft es ganz gut, denke ich. Denn was man liest und hört über die Wohnungssituation in japanischen Ballungsräumen, das läßt einen wirklich bangen vor der Wohnungssuche, und man stellt sich vor, in einem Wohn-Schlaf-Koch-Ess-Klo im 10. Stock leben zu müssen, 'zig Kilometer entfernt zum Arbeitsplatz. Nach meiner eigenen Erfahrung jedoch ist es in Tokyo oder Osaka auch nicht schwerer als in München, eine Wohnung zu finden, und auch nicht unbedingt viel teurer, wenn man nicht Quadratmeter zählt, sondern nutzbaren Wohnraum.

Was in Japan leider wenig üblich zu sein scheint, sind Wohngemeinschaften. Aber die meisten Japaner legen viel Wert auf eine eigene Wohnung und ihre Privatsphäre, und so ist das Angebot sehr gering ... zum Glück aber auch die Nachfrage.

Als kurzfristige Alternative empfehlen sich auch die sog. „Gaijin Houses“, in denen man für Tage, Wochen, aber auch für einige Monate ein relativ preiswertes Zimmer mieten kann. Es gibt auch Leute, die dort Jahre verbringen, aber weshalb, das verstehen diese meist selber nicht.

OK, dort, wo ich jetzt wohne, lebt es sich eigentlich ganz komfortabel, obwohl es ein bisschen eng ist. Dafür kann man nicht soviel Unordnung machen. Die Kimaanlage fehlt genausowenig wie der Reiskocher ... wo kriegt man das schon in München? Und im Bad hat man von der Toilette aus alle Installationen in Reichweite. Als Camper dürfte man sich in Japan wie im Urlaub fühlen! 