= Rebirth of the Karida blog
:published_at: 2010-12-16
:hp-tags: Japan, Karida, Osaka

As you can see on the date of the last blog post: there hasn't been any article for a looong time. And those articles were actually part of my old website, which I had turned off several months ago.
A lot of things have changed since then, but one hasn't: I'm still living in Japan and I'm still struggling with the cultural differences ;-) ... at least from time to time.

Actually I'm too busy for writing a blog. But maybe that's the reason why I sat down, loaded the old website content backup into a database and extracted the content to be able to import it into this new blog. Well, you're normally doing this kind of useless stuff when you actually have no time for it, right?

So now it's back: the old blog. And I can write new posts as before ... and from time to time rant about what drives me nuts here in Japan. My wife will appreciate when I find another channel to let it out ;-)
There might be articles in English from time to time, but mostly I will try to write in German, so my family can stay up-to-date with what is going on overhere. 